fill out L/A/B to RGB conversion script

diff --git a/bin/lab_color_to_rgb_jpeg b/bin/lab_color_to_rgb_jpeg
--- a/bin/lab_color_to_rgb_jpeg
+++ b/bin/lab_color_to_rgb_jpeg
@@ -1,10 +1,106 @@
 #!/bin/sh
 
-count=1
-for x 
-do
-  echo "`printf "%2d" $count` `date +%FT%T%z` $x"
-  new_name=`echo $x | sed 's!tif$!jpg!'`
-  convert $x -colorspace LAB -quality 95% -colorspace RGB /Volumes/EIT_MARGE/color_jpgs/$new_name
-  count=$(( $count + 1 ))
+read -r -d '' HELP <<-'EOF'
+Convert all L/A/B TIFF's in IN_DIR to RGB JPEG's, writing the to OUT_DIR
+EOF
+# functions
+SHOT_SEQ_PATTERN="^[0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9][0-9]$"
+valid_shot_sequence() {
+  echo "$1" | grep "$SHOT_SEQ_PATTERN" > /dev/null
+}
+
+### TEMPFILES
+# From:
+#   http://stackoverflow.com/questions/430078/shell-script-templates
+# create a default tmp file name
+tmp=${TMPDIR:-/tmp}/prog.$$
+# delete any existing temp files
+trap "rm -f $tmp.?; exit 1" 0 1 2 3 13 15
+# then do
+#   ...real work that creates temp files $tmp.1, $tmp.2, ...
+
+#### USAGE AND ERRORS
+cmd=`basename $0 .sh`
+export SPINDLE_COMMAND=$cmd
+source `dirname $0`/spindle_functions
+
+usage() {
+   echo "Usage: $cmd [-h] IN_DIR OUT_DIR"
+   echo ""
+   echo "OPTIONS"
+   echo ""
+   echo "   -h             Display help message"
+   echo "   -v             Display Spindle version"
+   echo ""
+}
+
+### CONSTANTS
+
+### VARIABLES
+IN_DIR=
+OUT_DIR=
+
+### OPTIONS
+while getopts ":hv" opt; do
+  case $opt in
+    h)
+      usage 
+      version
+      help
+      exit 1
+      ;;
+    v)
+      version
+      exit 1
+      ;;
+    \?)
+      echo "ERROR Invalid option: -$OPTARG" >&2
+      echo ""
+      usage
+      exit 1
+      ;;
+  esac
 done
+
+shift $((OPTIND-1))
+
+### THESCRIPT
+# grab package directoy and confirm it exists
+IN_DIR=`package_dir $1`
+if [ $? -ne 0 ]; then
+  error "Error finding IN_DIR"
+fi
+
+OUT_DIR=`package_dir $2`
+if [ $? -ne 0 ]; then
+  error "Error finding OUT_DIR"
+fi
+
+### HARVEST METADATA
+# change to the package dir
+
+file_list=$tmp.1
+find $IN_DIR -name \*_PSH_color.tif -print -o \
+  -name \*_CCD_CCC-\*.tif -print | sort > $file_list
+
+if [ ! -s $file_list ]; then
+  error "No PhotoShoot color TIFF's found under $IN_DIR"
+fi
+
+total=`wc -l $file_list | awk '{ print $1 }'`
+count=0
+report_count $count $total 0
+while read file 
+do
+  new_name=`echo $file | sed 's!tif$!jpg!'`
+  base=`basename $new_name`
+  convert $file -colorspace LAB -quality 95% -colorspace RGB $OUT_DIR/$base
+  count=$(( $count + 1 ))
+  report_count $count $total 0 $base
+done < $file_list
+
+### EXIT
+# http://stackoverflow.com/questions/430078/shell-script-templates
+rm -f $tmp.?
+trap 0
+exit 0
