functions for finding images

diff --git a/bin/spindle_functions b/bin/spindle_functions
--- a/bin/spindle_functions
+++ b/bin/spindle_functions
@@ -464,19 +464,85 @@ has_prep_json_files() {
 }
 
 # For SHOT_SEQUENCE (e.g., 0001_000123), find the corresponding
+# DNG dir in CAPTURE_DIR.
+#
+# Usage: locate_dng_dir SHOT_SEQUENCE CAPTURE_DIR
+locate_dng_dir() {
+  ldd_seq=$1
+  ldd_cap_dir=$2
+
+  # we could assume that the folder is <CAPTURE_DIR>/RAWS/<SHOT_SEQ>. This is
+  # almost always correct; *but* I don't trust that they won't name the RAWS
+  # folder `Raws` or `DNGS` or some other thing in the future. To be safe(?)
+  # let's just find the UV DNG for the SHOT_SEQUENCE and use its folder.
+  ldd_uv_dng=`locate_uv_dng $ldd_seq $ldd_cap_dir`
+  if [ $? -eq 0 ]; then
+    basename $ldd_uv_dng
+    return 0
+  else
+    echo "Could not locate DNG dir for $ldd_seq" >&2
+    return 1
+  fi
+}
+
+# For SHOT_SEQUENCE (e.g., 0001_000123), find the corresponding
+# flattened TIFF dir in CAPTURE_DIR.
+#
+# Usage: locate_dng_dir SHOT_SEQUENCE CAPTURE_DIR
+locate_tiff_dir() {
+  ltd_seq=$1
+  ltd_cap_dir=$2
+
+  # we could assume that the folder is <CAPTURE_DIR>/FLATTENED/<SHOT_SEQ>. This is
+  # almost always correct; *but* I don't trust that they won't name the FLATTENED
+  # folder `Flattened` or `TIFFS` or some other thing in the future. To be safe(?)
+  # let's just find the UV TIFF for the SHOT_SEQUENCE and use its folder.
+  ltd_uv_dng=`locate_uv_dng $ltd_seq $ltd_cap_dir`
+  if [ $? -eq 0 ]; then
+    basename $ltd_uv_dng
+    return 0
+  else
+    echo "Could not locate TIFF dir for $ltd_seq" >&2
+    return 1
+  fi
+}
+
+# For SHOT_SEQUENCE (e.g., 0001_000123), find the corresponding
 # UV DNG in CAPTURE_DIR.
 #
 # Usage: locate_uv_dng SHOT_SEQUENCE CAPTURE_DIR
 locate_uv_dng() {
   lud_seq=$1
   lud_cap_dir=$2
+  # We assume that the UV DNG is image *_001.dng. This is risky,
+  # but not too risky.
   lud_file=`find $lud_cap_dir -name "${lud_seq}[+_]*_001.dng"`
   lud_count=`echo "$lud_file" | wc -w | sed 's/ //g'`
   echo lud_file
   if [ $lud_count -eq 1 ]; then
     return 0
   else
-    echo "Expected 1 file; found $lud_count" >&2
+    echo "Expected 1 UV DNG file; found $lud_count" >&2
+    return 1
+  fi
+}
+
+# For SHOT_SEQUENCE (e.g., 0001_000123), find the corresponding
+# UV TIFF in CAPTURE_DIR.
+#
+# Usage: locate_uv_dng SHOT_SEQUENCE CAPTURE_DIR
+locate_uv_tiff() {
+  lut_seq=$1
+  lut_cap_dir=$2
+  # We assume that the UV DNG is image *_001.dng. This is risky,
+  # but not too risky.
+  lut_file=`find $lut_cap_dir -name "${lut_seq}[+_]*_001_F.tif"`
+  lut_count=`echo "$lut_file" | wc -w | sed 's/ //g'`
+  echo lut_file
+  if [ $lut_count -eq 1 ]; then
+    return 0
+  else
+    echo "Expected 1 UV TIFF file; found $lut_count" >&2
     return 1
   fi
 }
@@ -595,6 +661,52 @@ cmpActualToLogged() {
       error_no_exit "NO_SUCH_FILE  $file"
     done
     
+    return 1
+  fi
+}
+
+# AP DAT File Processing Rotation - Get from UV EXIF
+# AP ID Parent File - Get from Ken (color file header?)
+# MB455RB_002
+# MB470LB_003
+# MB505Cy_004
+# MB535Gr_005
+# MB570Am_006
+# MB625Rd_007
+WAVELENGTHS=`cat<<EOF
+455 002
+470 003
+505 004
+535 005
+570 006
+625 007
+EOF`
+parent_files() {
+  pf_color_tiff=$1
+  if [ -f $pf_color_tiff ]; then
+    pf_shot_seq=`extract_shot_sequence $pf_color_tiff`
+    
+    pf_tiffs=
+    pf_tiff_list=`basename $pf_color_tiff`/${pf_shot_seq}_tiff_list.txt
+    if [ -f $pf_tiff_list ]; then
+      echo $WAVELENGTHS | while read pair
+      do
+        pf_wave=`echo $pair | awk '{ print $1 }'`
+        pf_index=`echo $pair | awk '{ print $2 }'`
+        pf_next_tiff=`grep "_${pf_index}_F.tif" $pf_tiff_list`
+        if echo "$pf_next_tiff" | grep "$pf_wave" >/dev/null ; then
+          pf_tiffs="${pf_tiffs} `basename $pf_next_tiff`
+        else
+          invalid "Expected wave/index pair: ${pf_wave}/${pf_index}; found $pf_next_tiff"
+        fi
+      done
+    else
+      echo "Expected TIFF list not found: $pf_tiff_list" >&2
+      return 1
+    fi
+    return 0
+  else
+    echo "Could not find color TIFF file: $pf_color_tiff" >&2
     return 1
   fi
 }
