capture receipt handles new requirements for RAW and DEVELOPED:
RAWS/DNGs now checked for checksums, but not checked into repo.
JPEG images in developed folder now have checksums created and
are checked into repo. The JPEGs will be used as sources for
thumbnail images to be added to archival distros with the
flattened TIFF images.

diff --git a/bin/spindle_functions b/bin/spindle_functions
--- a/bin/spindle_functions
+++ b/bin/spindle_functions
@@ -189,6 +189,10 @@ valid_capture_dir() {
     echo "FLATTENED directory not found; expected $vcd_dir/FLATTENED" >&2
     return 1
   fi
+  if [ ! -d "$vcd_dir/DEVELOPED" ]; then
+    echo "DEVELOPED directory not found; expected $vcd_dir/DEVELOPED" >&2
+    return 1
+  fi
   return 0
 }
 
