update for receipt mode

diff --git a/bin/verify_checksums b/bin/verify_checksums
--- a/bin/verify_checksums
+++ b/bin/verify_checksums
@@ -88,7 +88,7 @@ usage() {
 }
 
 ### LOGGING
-logfile=LOG_${cmd}.log
+logfile=RECPT_checksums.log
 
 log() {
     echo "`date +%Y-%m-%dT%H:%M:%S` [$cmd] $1" >> $logfile
@@ -104,7 +104,6 @@ log_error() {
 # the name of the manifest in each dir
 MANIFEST_FILE=manifest-md5s.txt
 # image file extensions
-FILE_TYPES="jpg JPG jpeg JPEG tiff TIFF tif TIF"
 
 ### VARIABLES
 # the package dir
@@ -155,13 +154,11 @@ fi
 message "Using MD5 command: $MD5_CMD"
 
 # grab package directoy and confirm it exists
-PACKAGE_DIR=$1
-if [ -z "$PACKAGE_DIR" ]; then
-  message "No PACKAGE_DIR provided. Using '.'"
-  PACKAGE_DIR=.
-elif [ ! -d $PACKAGE_DIR ]; then
-  error "PACKAGE_DIR not found: $PACKAGE_DIR"
+PACKAGE_DIR=`package_dir $1`
+if [ $? -ne 0 ]; then
+  error "Error finding package directory"
 fi
+message "PACKAGE_DIR is $PACKAGE_DIR"
 
 # make sure there's a data directory in PACKAGE_DIR
 DATA_DIR=$PACKAGE_DIR/data
@@ -209,29 +206,10 @@ manifest_files=$tmp.2
 awk '{ print $2 }' $MANIFEST_FILE | sed 's/\*//' | sort > $manifest_files
 diff_file=$tmp.3
 
-# run diff
-diff $data_files $manifest_files > $diff_file
-# if diff errors out, then something's not right; dig out the differences
+cmpActualToLogged $data_files $manifest_files
 if [ $? -ne 0 ]; then
-  error_no_exit "Manifest does not match directory contents"
-
-  NOT_LISTED=`grep "^<" $diff_file | sed 's/<//'`
-  for file in $NOT_LISTED
-  do
-    msg="`printf "%-${file_width}s" $file` NOT IN MANIFEST"
-    log_error "$msg"
-    error_no_exit "$msg"
-  done
-
-  NOT_FOUND=`grep "^>" $diff_file | sed 's/>//'`
-  for file in $NOT_FOUND
-  do
-    msg="`printf "%-${file_width}s" $file` NO SUCH FILE"
-    log_error "$msg"
-    error_no_exit "$msg"
-  done
-  message "Errors logged to `pwd`/$error_file"
-  fail "MANIFEST LIST DOES NOT MATCH data DIRECTORY CONTENTS"
+  log_invalid $logfile "MANIFEST_MISMATCH"
+  fail "MANIFEST_MISMATCH"
 fi
 
 ### VERIFY THE CHECKSUMS
@@ -242,40 +220,42 @@ if echo "$MD5_CMD" | grep "md5sum" >/dev/null 2>&1 ; then
   # run the command
   $MD5_CMD -c $MANIFEST_FILE
   if [ $? -eq 0 ]; then
-    log "ALL VALID"
+    log "ALL_VALID"
     message "Completion logged to `pwd`/$logfile"
-    success "data is valid"
+    success "ALL_VALID"
   else
-    log_error "ERRORS FOUND"
-    message "Errors logged to `pwd`/$error_file"
-    fail "ERRORS FOUND"
+    log "ERRORS_FOUND"
+    message "Errors logged to `pwd`/$logfile"
+    fail "ERRORS_FOUND"
   fi
-fi
-
-# if we got this far, we have to use md5 and check each entry individually 
-bad_checksum=
-while read file
-do
-  line=`$MD5_CMD -r $file`
-  sum=`echo $line | awk '{ print $1 }'`
-  path=`echo $line | sed 's/\*//' | awk '{ print $2 }'`
-  if grep "$sum [* ]\?$path" $MANIFEST_FILE >/dev/null 2>&1 ; then
-    echo "$file: OK"
-  else
-    echo "$file: FAILED"
-    bad_checksum="$bad_checksum $file"
-  fi
-done < $data_files
-
-if [ -n "$bad_checksum" ]; then
-  log_error "ERRORS FOUND"
-  message "Errors logged to `pwd`/$error_file"
-  fail "ERRORS FOUND"
 else
-  log "ALL VALID"
-  message "Completion logged to `pwd`/$logfile"
-  success "data is valid"
+  # if we got this far, we have to use md5 and check each entry individually 
+  bad_checksum=
+  while read file
+  do
+    line=`$MD5_CMD -r $file`
+    sum=`echo $line | awk '{ print $1 }'`
+    path=`echo $line | sed 's/\*//' | awk '{ print $2 }'`
+    if grep "$sum [* ]\?$path" $MANIFEST_FILE >/dev/null 2>&1 ; then
+      echo "$file: OK"
+    else
+      echo "$file: FAILED"
+      bad_checksum="$bad_checksum $file"
+      log_invalid $logfile "BAD_CHECKSUM $file"
+    fi
+  done < $data_files
+
+  if [ -n "$bad_checksum" ]; then
+    log "ERRORS_FOUND"
+    message "Errors logged to `pwd`/$logfile"
+    fail "ERRORS_FOUND"
+  else
+    log "ALL_VALID"
+    message "Completion logged to `pwd`/$logfile"
+    success "ALL_VALID"
+  fi
 fi
+
 
 ### EXIT
 # http://stackoverflow.com/questions/430078/shell-script-templates
